# Generated by Django 3.2.23 on 2024-01-25 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TextField(choices=[('3-5', '15-17'), ('5-7', '17-19'), ('7-9', '19-21')], max_length=255),
        ),
    ]
