# Generated by Django 3.2.23 on 2024-01-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20240125_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.TextField(choices=[('1', 'Table at the Ice Bar'), ('2', 'Table around Ice-Fountain'), ('3', 'Table With a View of Torne River'), ('4', 'Table Made Of Ice')], max_length=255),
        ),
    ]
